version: "2"
services:
  webgrabplus:
    image: linuxserver/webgrabplus
    container_name: webgrabplus
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - ./webgrab/config:/config
      - ./webgrab/data:/data
    restart: unless-stopped
  server:
    image: pzender/eng-server
    build: ./server
    container_name: server
    ports:
      - 5000:5000
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - ./webgrab/data:/data
  client:
    image: pzender/eng-client
    build: ./client
    container_name: client
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Europe/Warsaw
    volumes: 
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  db:
    image: mcr.microsoft.com/mssql/server
    container_name: db
    ports:
      - 1433:1433
    volumes:
      -  ./.mssql:/var/opt/mssql
    environment:
      - TZ=Europe/Warsaw
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
      - MSSQL_PID=Express
    restart: unless-stopped

# yourStrong(!)Password